### ISSUE TITLE
Error: Volver al inicio del nivel (Prueba 1)

### ISSUE THREAD

**Issue by Adriaaan63** [Proyectos1-FDI-UCM/c2223-Grupo06#1]
### Descripción
Este error se produce cuando se abre el menú de pausa mientras estás jugando y se le da a inicio el juego se bloquea.

### Pasos 
Pasos error cuando le das a inicio desde el menú de pausa:
1. Paso 1: estando en cualquier parte del nivel, se abre el menú de pausa
2. Paso 2: se le clica al botón de inicio, y de esta forma el juego se bloquea.

### Captura de pantalla o vídeo
https://youtu.be/6rpcHYJCp_w

**Comment by cyntrist** [comment]
Solucionado, en la build de pruebas no cambiaba bien de estado desde pausa a game a través de ese botón en concreto.
