### ISSUE TITLE
Problemas al interactuar con las plataformas

### ISSUE THREAD

**Issue by Mikeey84** [Proyectos1-FDI-UCM/c2223-Grupo06#6]
### Pasos
          1. Ponerse encima de una plataforma.
          2. Intentar pasar al suelo desde la plataforma.

**Comment by cyntrist** [comment]
No he conseguido replicar este problema, es en alguna zona concreta y/o el 100% de las veces? Si tienes algún vídeo de lo que ocurre y dónde me ayudaría mucho.
