### ISSUE TITLE
Error: Interacción con NPC’S (Prueba 2)

### ISSUE THREAD

**Issue by Adriaaan63** [Proyectos1-FDI-UCM/c2223-Grupo06#7]
### Descripción

Mientras se avanza en el nivel y van apareciendo los npc’s, cada vez que se interactúan con ellos y mientras hablas intentas soltar partes del juego, este se bloquea. Además, la el juego también se bloque cuando se interactúa con el jugador mientras te mueves.

#### Pasos error interacción mientras pulsas teclas de soltar objetos: 
1.  Paso 1: Una vez se llega a la zona donde se aprende a saltar, llegas al Npc
2. Paso 2: la primera interacción con el funciona correctamente 
3. Paso 3: Vuelves a interaccionar con él, y mientras hablas con él intentas soltar una parte del juego.
4. Paso 4: El juego se bloquea y no te permite moverte ni nada. 

####Pasos error interacción mientras pulsas teclas de movimiento: 
1. Paso 1: Una vez se llega a la zona donde se aprende a saltar, llegas al Npc
2. Paso 2: interactúas con el npc mientras se mueves a la derecha. 
3. Paso 3: Comprobaras que el jugador no se frena y continúa andando
4. Paso 4: No te permite moverte, se bloque el juego. 

### Captura de pantalla o vídeo
https://youtu.be/0-zaH7jJmWk

**Comment by nievesag** [comment]
El segundo error ya está arreglado, el primero no he conseguido replicarlo, podrías detallar más qué hiciste / si crees que pasa bajo alguna circunstancia más concreta
