### ISSUE TITLE
Error collider plataforma

### ISSUE THREAD

**Issue by MarcosPRC** [Proyectos1-FDI-UCM/c2223-Grupo06#8]
**Descripción**
El error ocurre al saltar al borde de la plataforma y mantener pulsada la flecha derecha, lo que ocurre es que nos quedamos pillados en la plataforma hasta que soltamos la flecha.

**Pasos para reproducir el error**
1.Llegar a la plataforma indicada en el video.
2.Intentar saltar al borde.
3.mantener la flecha derecha.

**Video del error**
[![Error](https://img.youtube.com/vi/bfzK-_ZH13I/0.jpg)](https://youtu.be/bfzK-_ZH13I
)

**Comment by cyntrist** [comment]
Solucionado, faltaba aplicarle el material al collider de la plataforma por peso.
