### ISSUE TITLE
Final de la plataforma

### ISSUE THREAD

**Issue by MarcosPRC** [Proyectos1-FDI-UCM/c2223-Grupo06#9]
**Descripción**
Cuando llegamos a la plataforma en la que ocurre el error 3 se refleja en el sprite una longitud de la plataforma que no se asemeja al collider puesto, por lo que te caes antes de llegar al borde.

**Pasos para reproducir el error**

1.Llegar a la plataforma indicada en el video(una de las primeras salas).
2.Quedarte en el final de la plataforma.

**Video del error**
[![Texto alternativo](https://img.youtube.com/vi/wSCQwpESQOw/0.jpg)](https://youtu.be/wSCQwpESQOw
)

**Comment by cyntrist** [comment]
Solucionado, el prefab tenía el collider demasiado pequeño.
